[package]
name = "reprof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemalloc_pprof.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3.18"
tikv-jemallocator = { workspace = true, features = ["profiling"] }
tikv-jemalloc-ctl = { workspace = true }
clap = { version = "4.5.2", features = ["derive"] }
fxprof-processed-profile.workspace = true
wholesym.workspace = true
