[package]
name = "jeprof-firefox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxprof-processed-profile.workspace = true
jemalloc_pprof.workspace = true

